### ISSUE TITLE
Client side is not optional

### ISSUE THREAD

**Issue by ItsTeraBytes** [PrincessCyanMarine/SimpleVeinminer#12]
The mod claims that clients needing this mod is optional but it's not. Players cannot join without this mod. I have provided a screenshot.

![image](https://github.com/PrincessCyanMarine/SimpleVeinminer/assets/88017555/35369a77-05ac-4db7-bccb-30a164c22358)

**Comment by PrincessCyanMarine** [comment]
Failed to reproduce

**Comment by PrincessCyanMarine** [comment]
* Problem occurs if player has fabric API installed
