### ISSUE TITLE
Not compatible with fabric mod loader version 0.15.0

### ISSUE THREAD

**Issue by papamaionise** [PrincessCyanMarine/SimpleVeinminer#15]
Mod isn't compatible with fabric mod loader version 0.15.0
this is a must have mod so please update.
thankyou

**Comment by papamaionise** [comment]
please update the 1.20.1 version to be compatible with fabric mod loader 0.15.0 and above

**Comment by PrincessCyanMarine** [comment]
The latest version should be working for Minecraft 1.20.3 and 1.20.4 using fabric 1.15.3

**Comment by PrincessCyanMarine** [comment]
(didn't test for other fabric versions)

**Comment by papamaionise** [comment]
> The latest version should be working for Minecraft 1.20.3 and 1.20.4 using fabric 1.15.3

1.20.1 is like the most popular version for modding would you please make a version compatible with modloader 0.15.0 for 1.20.1
please

**Comment by PrincessCyanMarine** [comment]
https://www.curseforge.com/minecraft/mc-mods/simple-veinminer/files/4984906 (feel free to reopen if there are any problems)

**Comment by papamaionise** [comment]
> https://www.curseforge.com/minecraft/mc-mods/simple-veinminer/files/4984906 (feel free to reopen if there are any problems)

Thanks a lot
the day since It got removed from my server
all friends stopped playing
