### ISSUE TITLE
hi im playing on 1.20.1 

### ISSUE THREAD

**Issue by Ljbest30** [PrincessCyanMarine/SimpleVeinminer#18]
and I can use the vein miner but my friend doesn't have the same key bind menu also he cant use the command to get it so how can he get vein miner

**Comment by PrincessCyanMarine** [comment]
Assuming you are both playing on a server with the mod installed (or playing in LAN with the host having the mod), the gamerule "doServerSideVeinmining" should allow anyone on the server to veinmine when shifting, whether they have the mod installed or not. However, if he wants the keybind and commands he also needs to install the mod

**Comment by Ljbest30** [comment]
thank you
