### ISSUE TITLE
feature request: "/" for filterlist

### ISSUE THREAD

**Issue by Knito58** [PrincessCyanMarine/SimpleVeinminer#21]
#c:ores does not contain modded ores. If I wanted to whitelist techreborn:mineable/pickaxe that won't work. I think it is the "/" slash that is not recognized as a pattern member.
For to veinmine techreborn ores I need to find something without slash.

As F3 tells me, #techreborn:needs_stone_tool and #techreborn:needs_iron_tool do work.

It would be much easier to config if slashed categories were allowed in the list.

But we can get around this as long as the mod offers enough non slashed block categories.

**Comment by PrincessCyanMarine** [comment]
1.4.6 adds more ore types to the #c:ores list by default
Also made it possible to use "/" for filters

**Comment by Knito58** [comment]
Thank you.
