### ISSUE TITLE
[Bug] Durability of *any* hand-held item (including armor) will be used when veinmining

### ISSUE THREAD

**Issue by MrAgeo** [PrincessCyanMarine/SimpleVeinminer#23]
Using:
- SimpleVeinminer 1.4.6
- Fabric loader 0.15.7
- Fabric API 0.96.4
- MC 1.20.4

When "Can only veinmine with the right tool" is disabled and I try to veinmine any block that can be mined by hand (such as dirt, hay bales, pumpkins, etc.) with any other item that has durability (e.g. flint and steel, iron helmet, shield, fishing rod, etc.), this item will decrease its durability.

**Note:** Some items' durability -like shears- will decrease by N+1 instead of the number of veinmined blocks (maybe it's related to #22).

---
Example of the bug:

### SimpleVeinminer detects 4 blocks
![SimpleVeinminer detects 4 blocks](https://github.com/PrincessCyanMarine/SimpleVeinminer/assets/29012432/2ad65ca5-3a22-4ba4-bbbf-121fd286a57e)

### Before veinmining with an iron helmet
![Before veinmining with an iron helmet](https://github.com/PrincessCyanMarine/SimpleVeinminer/assets/29012432/dab40255-68c7-49b8-8759-75d6c0b5970d)

### After veinmining with the iron helmet
![After veinmining with the iron helmet](https://github.com/PrincessCyanMarine/SimpleVeinminer/assets/29012432/1d1d8363-93a6-4a12-a48f-c3c371b2f032)

Thanks in advance for your help! :D

**Comment by PrincessCyanMarine** [comment]
1.4.7 should fix both problems (issues #22 and #23)

But I made the fixes quickly and it is 1 am, so I'm going to leave both issues open for now (I did test it, and it seems fine. But just in case)

**Comment by MrAgeo** [comment]
Indeed both bugs are fixed! Thank you very much! :D

I tested every item that has durability with different types of blocks and it behaves just like vanilla :)

A summary of what I did is: Take an item, veinmine N blocks, see if the durability decreased by N [or by 2 + swordMultiplier*(N-1) in case of tridents and swords], then see if the block should have dropped something (e.g breaking a gold ore with a wood pickaxe shouldn't drop anything), and repeat with another item.

EDIT: Removed mention of issue 24

---
##  Description of the tests

### Regarding this issue (#23)
- Tested all items with sand

### Regarding issue #22
Tested:
- Axes with logs
- Pickaxe tiers with stone, iron ore, gold ore, diamond block & netherite block 
- Hoes with hay blocks
- Swords & shears with cobwebs
- Shovels with sand
- Tridents with sand and dirt

**Note:** The item list is from https://minecraft.fandom.com/wiki/Durability
