### ISSUE TITLE
VeinMiner not working on Multiplayer 

### ISSUE THREAD

**Issue by Max02765** [PrincessCyanMarine/SimpleVeinminer#3]
I try to use a Iron Pickaxe while pressing the button to enable VeinMiner it shows me the white borders and the selected blocks, but it doesn't mine the entire ores. I am not sure if the server also needs to have the mod or Fabric installed, as that is not the case. I do not think that that is needed as it doesn't say under the "Enchantments and multiplayer" section. It works fine in a singleplayer world.

**Comment by PrincessCyanMarine** [comment]
It needs to be installed on the server
Otherwise, that would make the mod into a cheat and probably kick/ban you from servers when trying to use it
I've updated the mod description to specify said need
