### ISSUE TITLE
Shape Mining backport for 1.18.2

### ISSUE THREAD

**Issue by recon88** [PrincessCyanMarine/SimpleVeinminer#7]
Can we get the shape mining for 1.18.2 as well?
Also can you add more shapes like Tunnels (1x2, 2x2, 3x3)? Depth should just depend on `maxBlocks`.

There's literally no mod that does everything... You either get shapes, highlighting or just a basic veinminer :/

**Comment by PrincessCyanMarine** [comment]
Shaped veinmined has been removed and there are currently no plans to readd it
